name: Git tag main

on:
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Verify run id
      run : echo Run Id $GITHUB_RUN_ID 
      
    - name: Set output
      id: vars
      run: |
        version=$(git tag -l | sort -V | tail -1)
        major=$(echo $version | grep -Eo "v[0-9]{1,}\." | sed -r "s/(v|\.)//g")
        major=$(( major + 1 ))
        minor=$(echo $version | grep -Eo "\.[0-9]{1,}\." | sed "s/\.//g")
        hotfix=$(echo $version | grep -Eo "\.[0-9]{1,}$" | sed "s/\.//g")
        new_version="v${major}.${minor}.${hotfix}"
        echo ::set-output name=new_version::${new_version}

    - name: Check output
      run: echo New version ${{ steps.vars.outputs.new_version }}
