name: Git tag main

on:
  pull_request:
    branches:
      - 'main'
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Verify run id
      run : echo Run Id $GITHUB_RUN_ID 
      
    - name: Set new tag
      id: vars
      run: |
        version=$(git tag -l | sort -V | tail -1)
        major=$(echo $version | grep -Eo "v[0-9]{1,}\." | sed -r "s/(v|\.)//g")
        major=$(( major + 1 ))
        minor='0'
        hotfix='0'
        new_version="v${major}.${minor}.${hotfix}"
        echo ::set-output name=new_version::${new_version}

    - name: Check new tag
      run: echo New version ${{ steps.vars.outputs.new_version }}

    - name: Create new tag
      uses: tvdias/github-tagger@v0.0.1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        tag: "${{ steps.vars.outputs.new_version }}"
