name: Git tag develop

on:
  pull_request:
    branches: 
      - 'main'
      - 'master'
      - 'develop*'
      - 'hotfix*'
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Verify run id
      run : echo Run Id $GITHUB_RUN_ID 

    - name: Set main version
      if: contains(github.ref, "master")
      id: vars
      run: |
        version=$(git tag -l | sort -V | tail -1)
        major=$(echo $version | grep -Eo "v[0-9]{1,}\." | sed -r "s/(v|\.)//g")
        major=$(( major + 1 ))
        minor='0'
        hotfix='0'
        new_version="v${major}.${minor}.${hotfix}"
        echo "Old version: ${version}, new version ${new_version}"
        echo ::set-output name=new_version::${new_version}

    - name: Set develop version
      if: contains(github.ref, "develop")
      id: vars
      run: |
        version=$(git tag -l | sort -V | tail -1)
        major=$(echo $version | grep -Eo "v[0-9]{1,}\." | sed -r "s/(v|\.)//g")
        minor=$(echo $version | grep -Eo "\.[0-9]{1,}\." | sed "s/\.//g")
        minor=$(( minor + 1 ))
        hotfix='0'
        new_version="v${major}.${minor}.${hotfix}"
        echo "Old version: ${version}, new version ${new_version}"
        echo ::set-output name=new_version::${new_version}

    - name: Set hotfix version
      if: contains(github.ref, "hotfix")
      id: vars
      run: |
        version=$(git tag -l | sort -V | tail -1)
        major=$(echo $version | grep -Eo "v[0-9]{1,}\." | sed -r "s/(v|\.)//g")
        minor=$(echo $version | grep -Eo "\.[0-9]{1,}\." | sed "s/\.//g")
        hotfix=$(echo $version | grep -Eo "\.[0-9]{1,}$" | sed "s/\.//g")
        hotfix=$(( hotfix + 1 ))
        new_version="v${major}.${minor}.${hotfix}"
        echo "Old version: ${version}, new version ${new_version}"
        echo ::set-output name=new_version::${new_version}

    - name: Create new tag
      uses: tvdias/github-tagger@v0.0.1
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        tag: "${{ steps.vars.outputs.new_version }}"
